```toml
# Existing secrets
EMAIL_ADDRESS = "kumari.kaushiki@eaiiadvisors.in"
EMAIL_PASSWORD = "Shubhu@2208"
EMAIL_SENT = "kumari.kaushiki@eaiiadvisors.in"

# NEW: Log Sheet ID
LOG_SHEET_ID = "https://docs.google.com/spreadsheets/d/1Wleb4aTjGF5OV5PDNoI7GzqNyD4TXDMyb9B-xFF5vL0/edit?usp=sharing"

# NEW: Service Account credentials (copy from your downloaded JSON file)
[gcp_service_account]
type = "service_account",
project_id = "water-monitor-system-488307",
private_key_id = "1da946b9a0feb705d183c49e2d10006e825bd8a6",
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDKDWVAAi8HrixB\nl6ESloZXZy2kBuZEPrPz4gEkgM/l057yWqsIkKoFCMqCetRdwQb89vRT7bJkx93X\n/1qDEmQ52sTTnLPDejFhUheTn26QuI6yQ59HDRYcp0glr8k/5LjtjcbRs7hgWowS\nmPcQiDUU7xfsJyNFo+OEPvJroJkrjIQs+jyunftawHpKzpwV4f/vBJ4ksB1qeUHi\n41T3u6l+b5vFhNlZxCQLvu8CS0sK02osd9novHIhBaMLdrfMOlREsPQJYVB7TAey\nvKSkgIcyX976RThz6cPHcb0GKDu1vA68SOxVxwOvRqfIT5dnQs9dJqIufB32AshZ\nt4/SUB0BAgMBAAECggEAJ6EU+Mb03nbE62CIERNA6ieshf1scHoz5WOwga5aGGO3\nSyWJYjatgitFPO5GdNUFP9xX85YtZSLmWhUVdZvH2KkV7cNQZsiyorntMeEVWIE6\nS7CDrvXcHmaY+ftOZ5++vakPE9ZCFXPtAUDLRIzSjHaQpJrQijoox6lo9r8bC7U8\ncW6zInahPsfbnbabdurAd+z8JoQEYfCLtq30z46yWDJ6dWGFgAHu7FXbTZPUCLnT\nYs5zcXXsOqIRuf454SqqaOzRWCnCxkLlxINz60fARi2xNKGcwtp7EY5vszvCf56M\n5uHC0hJEnmMLLyTDaD5VNyZ27UY6DXu+M5FgLJzk2QKBgQDt1NUy389GBNLAPdpc\nxKAYnD49OFVoYcHrIEcyv3VzPCDWs9LsyUHk/jDEIByI0wVENHCwZEOLTUSGJHfX\nM9gQ6dzjYk30W7Wou9zqDOMekkxcYC+0aEPqT9pWWJnn/ADKSXzrHQ0HHoAzuQUy\nhS060ol+DXW6Bpm4r2lx+rfqPwKBgQDZfNjUF1icxWV0J3AZ7LeeiW9shjjK0q9/\nuQ6KjKXuGwRZw76IhBetYdMBHG8st7Ve4EqXu/iHib2ZvASTabrRZ1na8Isn3Qjj\nI3YgMGCDtmH9y7LI03XGG6tKwyfYQkEsCvEYINhxvPSgjF0vDNREQCJq1f+XrsRm\n82e70OGovwKBgQCa3qEGQ9+BRNrH/H8ZMaDe5b9RtkFHe4D/T0GNtkcRBvKLXQXY\n0yVprGytCgwKvP8M7ukCtAeXynT4tP6k0Em+mcsQ9o60tJOSkOLGNiYfXj0DWk82\nNz8icWVIHOH7wonxL/F8WKqHHEF3bOAJidduGnMV9kXXIT0wmmkbo5vnmQKBgEEE\nWa3N7Oew+0tmHtUhNyNl4rGGzqOTqHN+VyKEOXadDQfoxKT7GDj07ad/YJz1rnrW\ngnYp83pRayTyWEvZZ8gCJZKWJoOcSHPevgmRbMjzVQgSRThUPvkifGq1PMwhwmnw\nO3MDHrGh01/Llm/iXfKpWaCmqOonjP9Z9MDpCQzxAoGBALxELn1Lc15+YA/WBe7Q\nEVUtvZMdo7sVDGedopaEA4xZpKgwuf+uk3cbzMkgpzvCsCXZtnF4q+N6zQcO2Ogt\nYTg6Pg93b3lkpIRwcXcVIlGtXQOISCjuLbeRTXBZj4mLdZpBY1yCSeFaOav/R0x5\neMlIxFJKyDJNPJvPTDPHG6UI\n-----END PRIVATE KEY-----\n",
client_email = "water-monitoring-app@water-monitor-system-488307.iam.gserviceaccount.com",
client_id = "101213988596292556070",
auth_uri = "https://accounts.google.com/o/oauth2/auth",
token_uri = "https://oauth2.googleapis.com/token",
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs",
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/water-monitoring-app%40water-monitor-system-488307.iam.gserviceaccount.com",

```

